Fix some code

diff --git a/hzclish b/hzclish
--- a/hzclish
+++ b/hzclish
@@ -159,7 +159,17 @@ CONFIG(){
         if ! (($custconfig)); then
             config="${confdir}/${zid}.config"
         fi
-        if [[ ! -f "${confdir}/defaultconfig" || "$(cat "${confdir}/defaultconfig" | wc -m)" == 0 ]] || (($setdefconf)); then
+
+        # if [[ "$(grep 'token=.\+' "$config")" ]]; then
+        source "$config"
+        if [[ "$token" ]]; then
+            echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Script appears to be registered previously" >&2
+            echo "Use -D option to delete auth and then -s to try again" >&2
+            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
+            exit 1
+        fi
+
+        if [[ ! -f "${confdir}/defaultconfig" || "$(wc -m "${confdir}/defaultconfig"|cut -d ' ' -f 1)" == 0 ]] || (($setdefconf)); then
             ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""Setting default config: $config""\e[m"
             echo "config=\"$config\"">"${confdir}/defaultconfig" && [[ -f "${confdir}/defaultconfig" ]] && chmod 600 "${confdir}/defaultconfig"
         fi
@@ -229,64 +239,57 @@ fi
 SETAUTH(){
     CONFIG
     source "$config"
-    if [[ "$(grep 'token=.' "$config")" ]]; then
-        echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Script appears to be registered previously" >&2
-        echo "Use -d option to delete auth and then -s to try again" >&2
-        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
-        exit 1
-    else
-        if ! [[ "$password" ]]; then
-            echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "This will be the only time you will be asked for your password"
-            echo "Your password will be stored plain in config file"
-            PASSWORD
-        fi
-        sed -i '/password=/d' "$config"
-        echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
-        if (($verbose)); then
-            echo -e "\e[0;36m""Password have been saved to $config""\e[m"
-        fi
-        
-        source "$config"
-        echo "Getting token..."
-        getauth=$(curl -ksSi --trace-ascii - \
-            -u "${login}:$password" \
-            --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie" \
-            -H "User-Agent: $useragent" \
-            "${hub}/api/z/1.0/abconfig")
-        token=$(echo "$getauth"|sed -n 's/^.*Authorization: Basic \(.*\)/\1/p1')
+    if ! [[ "$password" ]]; then
+        echo -e '\e[37;34m'"\e[1m[notice]\e[0m" "This will be the only time you will be asked for your password"
+        echo "Your password will be stored plain in config file"
+        PASSWORD
+    fi
+    sed -i '/password=/d' "$config"
+    echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
+    if (($verbose)); then
+        echo -e "\e[0;36m""Password have been saved to $config""\e[m"
+    fi
+    
+    # source "$config"
+    echo "Getting token..."
+    getauth=$(curl -ksSi --trace-ascii - \
+        -u "${login}:$password" \
+        --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie" \
+        -H "User-Agent: $useragent" \
+        "${hub}/api/z/1.0/abconfig")
+    token=$(echo "$getauth"|sed -n 's/^.*Authorization: Basic \(.*\)/\1/p1')
 
-        # unset getauth
-        if [[ "$token" ]]; then
-            sed -i '/token=/d' "$config"
-            echo "token=\"${token}\"">>"$config"
-            # unset token
-            if (($verbose)); then
-                echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Token saved"
-            fi
-        else
-            echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Getting token failed. Check/set your login/password/connection" >&2
+    # unset getauth
+    if [[ "$token" ]]; then
+        sed -i '/token=/d' "$config"
+        echo "token=\"${token}\"">>"$config"
+        # unset token
+        if (($verbose)); then
+            echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Token saved"
+        fi
+    else
+        echo -e '\e[37;31m'"\e[1m[error]\e[0m" "Getting token failed. Check/set your login/password/connection" >&2
 (($verbose)) && echo -e '\e[37;31m'"\e[1m[post]\e[0m" >&2 && echo "$getauth" >&2
 unset getauth
-            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
-            exitstatus=1
-        fi
+        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
+        exitstatus=1
+    fi
 
-        local error=''
-        error=$(echo "$getauth" | grep -io '^This api requires login')
-        [[ "$error" ]] || error=$(echo "$getauth" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
-        if [[ "$error" ]]; then
-            [[ "$token" ]] && echo 'but' >&2
-            unset token
-            echo -en '\e[37;31m'"\e[1m[error] \e[0m" >&2; echo -en "\e[0;31m" >&2; echo -n "$error" >&2; echo -e "\e[m" >&2
-            echo "Check/set your login/password/server and try again" >&2
-            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
-            exitstatus=1
-        fi
+    local error=''
+    error=$(echo "$getauth" | grep -io '^This api requires login')
+    [[ "$error" ]] || error=$(echo "$getauth" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
+    if [[ "$error" ]]; then
+        [[ "$token" ]] && echo 'but' >&2
+        unset token
+        echo -en '\e[37;31m'"\e[1m[error] \e[0m" >&2; echo -en "\e[0;31m" >&2; echo -n "$error" >&2; echo -e "\e[m" >&2
+        echo "Check/set your login/password/server and try again" >&2
+        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
+        exitstatus=1
+    fi
 
-        if (($exitstatus)); then
-            (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
-            exit $exitstatus
-        fi
+    if (($exitstatus)); then
+        (($verbose)) && echo -e "\e[0;36m""Exiting""\e[m"
+        exit $exitstatus
     fi
 }
 
@@ -373,7 +376,7 @@ GETPOST(){
     GETPOSTINIT(){
         if (($inlineauth)); then
             ! [[ "$password" ]] && PASSWORD
-            (($verbose)) && echo -e "\e[0;36m""Getting post ${mid%%&*}...""\e[m"
+            (($verbose)) && echo -e "\e[0;36m""Getting post ${req#*=}...""\e[m"
             curl -ksSi -u "${login}:$password" \
                 -H "User-Agent: $useragent" \
                 -H "Content-Type: application/json" \
@@ -381,7 +384,7 @@ GETPOST(){
                 "${hub}/api/z/1.0/item/full?$req" >"$post"
             unset password
         else
-            (($verbose)) && echo -e "\e[0;36m""Getting post ${mid%%&*}...""\e[m"
+            (($verbose)) && echo -e "\e[0;36m""Getting post ${req#*=}...""\e[m"
             curl -ksSi \
                 -H "Authorization: Basic $token" \
                 --cookie-jar "${confdir}/$cookie" --cookie "${confdir}/$cookie" \
@@ -392,26 +395,26 @@ GETPOST(){
             unset password
             unset token
         fi
-        cat "$post"|grep -iom1 '{\".*[^\]\(["}]\|\]\)}' >"$postbody"
-        local postbodylength=$(cat "$postbody" | wc -m)
+        grep -iom1 '{\".*[^\]\(["}]\|\]\)}' "$post" >"$postbody"
+        local postbodylength=$(wc -m "$postbody"|cut -d ' ' -f 1)
         if (($postbodylength)); then
-            pid=$(cat "$postbody"|"$jq" -r '.item|.[].id')
-            mid=$(cat "$postbody"|"$jq" -r '.item|.[].message_id')
-            posturl=$(cat "$postbody"|"$jq" -r '.item|.[].permalink')
+            pid=$("$jq" -r '.item|.[].id' "$postbody")
+            mid=$("$jq" -r '.item|.[].message_id' "$postbody")
+            posturl=$("$jq" -r '.item|.[].permalink' "$postbody")
             posturl2="$(echo -n "$posturl"|sed 's|^.*\(https\?://[^/]\+\)/.*|\1|')/display/$mid"
             if ! (($urlonly)); then
-                username=$(cat "$postbody"|"$jq" -r '.item|.[].author.name')
-                useraddr=$(cat "$postbody"|"$jq" -r '.item|.[].author.address')
-                userurl=$(cat "$postbody"|"$jq" -r '.item|.[].author.url')
+                username=$("$jq" -r '.item|.[].author.name' "$postbody")
+                useraddr=$("$jq" -r '.item|.[].author.address' "$postbody")
+                userurl=$("$jq" -r '.item|.[].author.url' "$postbody")
                 userhub=$(echo -n "$userurl"|sed 's|^.*https\?://\([^/]\+\)/.*|\1|')
-                posttitle=$(cat "$postbody"|"$jq" -r '.item|.[].title')
+                posttitle=$("$jq" -r '.item|.[].title' "$postbody")
             fi
         fi
     }
     GETPOSTINIT
     local error=''
-    error=$(cat "$post" | grep -io '^This api requires login')
-    [[ "$error" ]] || error=$(cat "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
+    error=$(grep -io '^This api requires login' "$post")
+    [[ "$error" ]] || error=$(grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*' "$post")
     if [[ "$error" ]]; then
         if [[ $retokened != 1 ]] && [[ $inlineauth != 1 ]]; then
             if ! (($quiet)); then
@@ -423,8 +426,8 @@ GETPOST(){
             RETOKEN
             GETPOSTINIT
             local error=''
-            error=$(cat "$post" | grep -io '^This api requires login')
-            [[ "$error" ]] || error=$(cat "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
+            error=$(grep -io '^This api requires login' "$post")
+            [[ "$error" ]] || error=$(grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*' "$post")
             if [[ "$error" ]]; then
                 echo -en '\e[37;31m'"\e[1m[error] \e[0m" >&2; echo -en "\e[0;31m" >&2; echo -n "$error" >&2; echo -e "\e[m" >&2
                 echo "Can't get post due authorization issue" >&2
@@ -445,7 +448,7 @@ GETPOST(){
         if ! (($urlonly)); then
             echo -e "\e[0;36m""$useraddr:""\e[m\n"
             [[ "$posttitle" ]] && echo -e "${posttitle}\n"
-            cat "$postbody"|"$jq" -r '.item|.[].body'
+            "$jq" -r '.item|.[].body' "$postbody"
             if ! (($quiet)); then
                 echo -e "\n\e[0;36m""post url: $posturl2""\e[m"
                 (($verbose)) && echo -e "\e[0;36m""post id: $pid""\e[m"
@@ -498,7 +501,7 @@ POST(){
             else
                 $EDITOR "$message"
             fi
-            msglength=$(cat "$message" | wc -m)
+            msglength=$(wc -m "$message"|cut -d ' ' -f 1)
             if ! (($msglength)); then
                 echo -e '\e[37;31m'"\e[1m[error]\e[0m" "The message is empty. Not posting message" >&2
                 echo "Not deleting the file \"$message\" in case it is not empty" >&2
@@ -536,7 +539,7 @@ POST(){
 # cat "$message"
 # echo
         # msg=$(cat "$message")
-        cat "$message" >"$msgbody"
+        cp "$message" "$msgbody"
 # echo msg "$msg"
 # echo 
 # echo 
@@ -645,24 +648,24 @@ POST(){
         fi
 # cat "$post"
 # exit
-        cat "$post"|grep -iom1 '{\".*[^\]\(["}]\|\]\)}' >"$postbody"
-        local postbodylength=$(cat "$postbody" | wc -m)
-        (($postbodylength)) && success=$(cat "$postbody"|"$jq" -r '.success')
+        grep -iom1 '{\".*[^\]\(["}]\|\]\)}' "$post" >"$postbody"
+        local postbodylength=$(wc -m "$postbody"|cut -d ' ' -f 1)
+        (($postbodylength)) && success=$("$jq" -r '.success' "$postbody")
         if [[ "$success" == "true" ]]; then
-            pid=$(cat "$postbody"|"$jq" -r '.item_id')
-            mid=$(cat "$postbody"|"$jq" -r '.item.mid')
-            posturl=$(cat "$postbody"|"$jq" -r '.item.plink')
-            posturl2=$(cat "$postbody"|"$jq" -r '.item.llink')
+            pid=$("$jq" -r '.item_id' "$postbody")
+            mid=$("$jq" -r '.item.mid' "$postbody")
+            posturl=$("$jq" -r '.item.plink' "$postbody")
+            posturl2=$("$jq" -r '.item.llink' "$postbody")
         fi
     }
     POSTINIT
-    error=$(cat "$post" | grep -io '^This api requires login')
-    [[ "$error" ]] || error=$(cat "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
+    error=$(grep -io '^This api requires login' "$post")
+    [[ "$error" ]] || error=$(grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*' "$post")
 # echo error "$error"
 # exit
     # if [[ "$error" ]]; then
     if [[ "$error" || "$success" == "false" ]]; then
-        [[ "$error" ]] || error=$(cat "$postbody"|"$jq" -r '.message')
+        [[ "$error" ]] || error=$("$jq" -r '.message' "$postbody")
         if [[ "$error" == 'no content' ]]; then
             if ! (($quiet)); then
                 echo -en '\e[37;31m'"\e[1m[error] \e[0m" >&2; echo -en "\e[0;31m"; echo -n "$error" >&2; echo -e "\e[m" >&2
@@ -681,10 +684,10 @@ POST(){
                 RETOKEN
                 local success=''; local error=''
                 POSTINIT
-                error=$(cat "$post" | grep -io '^This api requires login')
-                [[ "$error" ]] || error=$(cat "$post" | grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*')
+                error=$(grep -io '^This api requires login' "$post")
+                [[ "$error" ]] || error=$(grep -o '^HTTP/[[:digit:]]\.[[:digit:]] \+[3-9]\{1,3\}.*' "$post")
                 if [[  "$error" || "$success" == "false" ]]; then
-                    [[ "$error" ]] || error=$(cat "$postbody"|"$jq" -r '.message')
+                    [[ "$error" ]] || error=$("$jq" -r '.message' "$postbody")
                     echo -en '\e[37;31m'"\e[1m[error] \e[0m" >&2; echo -en "\e[0;31m"; echo -n "$error" >&2; echo -e "\e[m" >&2
                     echo "Can't post due authorization issue" >&2
                     echo "Check/set your login/password/server and try to post again" >&2
@@ -703,7 +706,12 @@ POST(){
     
     if [[ "$pid" ]]; then
         if ! (($quiet)); then
-            echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Message "$pid" posted"
+            if [[ "$pid" ]]; then
+                local id="$pid"
+            elif [[ "$mid" ]]; then
+                local id="$mid"
+            fi
+            echo -e '\e[37;32m'"\e[1m[success]\e[0m" "Message "$id" posted"
             echo -en "\e[0;36m""post url: ""\e[m"
         fi
         echo -e "\e[0;36m""$posturl2""\e[m"
@@ -721,9 +729,9 @@ POST(){
 
 # DELETE CONFIG & COOKIE
 DELETE(){
-        [[ "$config" ]] && source "$config" && unset password
-    ! (($quiet)) && echo Deleting: cookie: "${confdir}/$cookie", config: "$config"
-    [[ "$confdir" && "$zid" ]] && [[ -f "${confdir}/$cookie" ]] && /bin/rm -f "${confdir}/$cookie"
+    [[ "$config" ]] && source "$config" && unset password
+    ! (($quiet)) && echo Deleting: cookie: "${confdir}/${zid}.cookie", config: "$config"
+    [[ "$confdir" && "$zid" ]] && [[ -f "${confdir}/${zid}.cookie" ]] && /bin/rm -f "${confdir}/${zid}.cookie"
     [[ "$config" ]] && [[ -f "$config" ]] && /bin/rm -f "$config"
 }
 
